# Generated by Django 4.2.2 on 2023-06-21 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('SubjectID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Coefficient', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('GradeID', models.AutoField(primary_key=True, serialize=False)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Student.students')),
                ('Subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Student.subjects')),
            ],
        ),
    ]
